import { IGNORE_PATH_DIST, IGNORE_PATH_DOT_ANGULAR, IGNORE_PATH_DOT_HUSKY, IGNORE_PATH_DOT_IDEA, IGNORE_PATH_NODE_MODULES } from "@ogs/linter";

export const IGNORE_PATHS = [
	IGNORE_PATH_DOT_IDEA,
	IGNORE_PATH_DIST,
	IGNORE_PATH_DOT_ANGULAR,
	IGNORE_PATH_DOT_HUSKY,
	IGNORE_PATH_NODE_MODULES
];
